/**
 * Gets URL parameter value by name
 * @param {string} name - The parameter name to retrieve
 * @returns {string|null} The parameter value or null if not found
 */
function getUrlParameter(name) {
    const urlParams = new URLSearchParams(window.location.search);
    return urlParams.get(name);
}

/**
 * Shows the thank you page and hides the application form
 */
function showThankYouPage() {
    const formElement = document.getElementById('applicationForm');
    const thankYouElement = document.getElementById('thankYouPage');

    if (formElement && thankYouElement) {
        formElement.classList.add('hidden');
        thankYouElement.classList.remove('hidden');
    }
}

/**
 * Shows the application form and hides the thank you page
 */
function showApplicationForm() {
    const formElement = document.getElementById('applicationForm');
    const thankYouElement = document.getElementById('thankYouPage');

    if (formElement && thankYouElement) {
        formElement.classList.remove('hidden');
        thankYouElement.classList.add('hidden');
    }
}

/**
 * Checks if the page should show thank you message or form
 */
function checkSubmissionStatus() {
    const submitted = getUrlParameter('submitted');

    if (submitted === 'true') {
        showThankYouPage();
    } else {
        showApplicationForm();
    }
}

function syncDate() {
    // 1. Get the browser-standard ISO date (YYYY-MM-DD) from the picker
    var picker = document.getElementById('ui_date_picker');
    var isoDate = picker.value;

    if (!isoDate) {
        document.getElementById('00Na3000001BRnV').value = "";
        return;
    }

    // 2. Split it
    var parts = isoDate.split('-'); // [YYYY, MM, DD]

    // 3. Reformat for Salesforce
    var sfDate = parts[2] + '/' + parts[1] + '/' + parts[0];

    // 4. Assign to the HIDDEN input, NOT the date picker
    var hiddenField = document.getElementById('00Na3000001BRnV');
    hiddenField.value = sfDate;

    console.log("Hidden field updated to: " + hiddenField.value);
}

// Country options data
const countries = [
    { value: "", label: "--None--" },
    { value: "AF", label: "Afghanistan" },
    { value: "AX", label: "Aland Islands" },
    { value: "AL", label: "Albania" },
    { value: "DZ", label: "Algeria" },
    { value: "AD", label: "Andorra" },
    { value: "AO", label: "Angola" },
    { value: "AI", label: "Anguilla" },
    { value: "AQ", label: "Antarctica" },
    { value: "AG", label: "Antigua and Barbuda" },
    { value: "AR", label: "Argentina" },
    { value: "AM", label: "Armenia" },
    { value: "AW", label: "Aruba" },
    { value: "AU", label: "Australia" },
    { value: "AT", label: "Austria" },
    { value: "AZ", label: "Azerbaijan" },
    { value: "BS", label: "Bahamas" },
    { value: "BH", label: "Bahrain" },
    { value: "BD", label: "Bangladesh" },
    { value: "BB", label: "Barbados" },
    { value: "BY", label: "Belarus" },
    { value: "BE", label: "Belgium" },
    { value: "BZ", label: "Belize" },
    { value: "BJ", label: "Benin" },
    { value: "BM", label: "Bermuda" },
    { value: "BT", label: "Bhutan" },
    { value: "BO", label: "Bolivia, Plurinational State of" },
    { value: "BQ", label: "Bonaire, Sint Eustatius and Saba" },
    { value: "BA", label: "Bosnia and Herzegovina" },
    { value: "BW", label: "Botswana" },
    { value: "BV", label: "Bouvet Island" },
    { value: "BR", label: "Brazil" },
    { value: "IO", label: "British Indian Ocean Territory" },
    { value: "BN", label: "Brunei Darussalam" },
    { value: "BG", label: "Bulgaria" },
    { value: "BF", label: "Burkina Faso" },
    { value: "BI", label: "Burundi" },
    { value: "KH", label: "Cambodia" },
    { value: "CM", label: "Cameroon" },
    { value: "CA", label: "Canada" },
    { value: "CV", label: "Cape Verde" },
    { value: "KY", label: "Cayman Islands" },
    { value: "CF", label: "Central African Republic" },
    { value: "TD", label: "Chad" },
    { value: "CL", label: "Chile" },
    { value: "CN", label: "China" },
    { value: "CX", label: "Christmas Island" },
    { value: "CC", label: "Cocos (Keeling) Islands" },
    { value: "CO", label: "Colombia" },
    { value: "KM", label: "Comoros" },
    { value: "CG", label: "Congo" },
    { value: "CD", label: "Congo, the Democratic Republic of the" },
    { value: "CK", label: "Cook Islands" },
    { value: "CR", label: "Costa Rica" },
    { value: "CI", label: "Cote d'Ivoire" },
    { value: "HR", label: "Croatia" },
    { value: "CW", label: "Cura�ao" },
    { value: "CY", label: "Cyprus" },
    { value: "CZ", label: "Czechia" },
    { value: "DK", label: "Denmark" },
    { value: "DJ", label: "Djibouti" },
    { value: "DM", label: "Dominica" },
    { value: "DO", label: "Dominican Republic" },
    { value: "EC", label: "Ecuador" },
    { value: "EG", label: "Egypt" },
    { value: "SV", label: "El Salvador" },
    { value: "GQ", label: "Equatorial Guinea" },
    { value: "ER", label: "Eritrea" },
    { value: "EE", label: "Estonia" },
    { value: "SZ", label: "Eswatini" },
    { value: "ET", label: "Ethiopia" },
    { value: "FK", label: "Falkland Islands (Malvinas)" },
    { value: "FO", label: "Faroe Islands" },
    { value: "FJ", label: "Fiji" },
    { value: "FI", label: "Finland" },
    { value: "FR", label: "France" },
    { value: "GF", label: "French Guiana" },
    { value: "PF", label: "French Polynesia" },
    { value: "TF", label: "French Southern Territories" },
    { value: "GA", label: "Gabon" },
    { value: "GM", label: "Gambia" },
    { value: "GE", label: "Georgia" },
    { value: "DE", label: "Germany" },
    { value: "GH", label: "Ghana" },
    { value: "GI", label: "Gibraltar" },
    { value: "GR", label: "Greece" },
    { value: "GL", label: "Greenland" },
    { value: "GD", label: "Grenada" },
    { value: "GP", label: "Guadeloupe" },
    { value: "GT", label: "Guatemala" },
    { value: "GG", label: "Guernsey" },
    { value: "GN", label: "Guinea" },
    { value: "GW", label: "Guinea-Bissau" },
    { value: "GY", label: "Guyana" },
    { value: "HT", label: "Haiti" },
    { value: "HM", label: "Heard Island and McDonald Islands" },
    { value: "VA", label: "Holy See (Vatican City State)" },
    { value: "HN", label: "Honduras" },
    { value: "HU", label: "Hungary" },
    { value: "IS", label: "Iceland" },
    { value: "IN", label: "India" },
    { value: "ID", label: "Indonesia" },
    { value: "IQ", label: "Iraq" },
    { value: "IE", label: "Ireland" },
    { value: "IM", label: "Isle of Man" },
    { value: "IL", label: "Israel" },
    { value: "IT", label: "Italy" },
    { value: "JM", label: "Jamaica" },
    { value: "JP", label: "Japan" },
    { value: "JE", label: "Jersey" },
    { value: "JO", label: "Jordan" },
    { value: "KZ", label: "Kazakhstan" },
    { value: "KE", label: "Kenya" },
    { value: "KI", label: "Kiribati" },
    { value: "KR", label: "Korea, Republic of" },
    { value: "XK", label: "Kosovo" },
    { value: "KW", label: "Kuwait" },
    { value: "KG", label: "Kyrgyzstan" },
    { value: "LA", label: "Lao People's Democratic Republic" },
    { value: "LV", label: "Latvia" },
    { value: "LB", label: "Lebanon" },
    { value: "LS", label: "Lesotho" },
    { value: "LR", label: "Liberia" },
    { value: "LY", label: "Libya" },
    { value: "LI", label: "Liechtenstein" },
    { value: "LT", label: "Lithuania" },
    { value: "LU", label: "Luxembourg" },
    { value: "MO", label: "Macao" },
    { value: "MG", label: "Madagascar" },
    { value: "MW", label: "Malawi" },
    { value: "MY", label: "Malaysia" },
    { value: "MV", label: "Maldives" },
    { value: "ML", label: "Mali" },
    { value: "MT", label: "Malta" },
    { value: "MQ", label: "Martinique" },
    { value: "MR", label: "Mauritania" },
    { value: "MU", label: "Mauritius" },
    { value: "YT", label: "Mayotte" },
    { value: "MX", label: "Mexico" },
    { value: "MD", label: "Moldova, Republic of" },
    { value: "MC", label: "Monaco" },
    { value: "MN", label: "Mongolia" },
    { value: "ME", label: "Montenegro" },
    { value: "MS", label: "Montserrat" },
    { value: "MA", label: "Morocco" },
    { value: "MZ", label: "Mozambique" },
    { value: "MM", label: "Myanmar" },
    { value: "NA", label: "Namibia" },
    { value: "NR", label: "Nauru" },
    { value: "NP", label: "Nepal" },
    { value: "NL", label: "Netherlands" },
    { value: "NC", label: "New Caledonia" },
    { value: "NZ", label: "New Zealand" },
    { value: "NI", label: "Nicaragua" },
    { value: "NE", label: "Niger" },
    { value: "NG", label: "Nigeria" },
    { value: "NU", label: "Niue" },
    { value: "NF", label: "Norfolk Island" },
    { value: "MK", label: "North Macedonia" },
    { value: "NO", label: "Norway" },
    { value: "OM", label: "Oman" },
    { value: "PK", label: "Pakistan" },
    { value: "PS", label: "Palestine" },
    { value: "PA", label: "Panama" },
    { value: "PG", label: "Papua New Guinea" },
    { value: "PY", label: "Paraguay" },
    { value: "PE", label: "Peru" },
    { value: "PH", label: "Philippines" },
    { value: "PN", label: "Pitcairn" },
    { value: "PL", label: "Poland" },
    { value: "PT", label: "Portugal" },
    { value: "QA", label: "Qatar" },
    { value: "RE", label: "Reunion" },
    { value: "RO", label: "Romania" },
    { value: "RU", label: "Russian Federation" },
    { value: "RW", label: "Rwanda" },
    { value: "BL", label: "Saint Barth�lemy" },
    { value: "SH", label: "Saint Helena, Ascension and Tristan da Cunha" },
    { value: "KN", label: "Saint Kitts and Nevis" },
    { value: "LC", label: "Saint Lucia" },
    { value: "MF", label: "Saint Martin (French part)" },
    { value: "PM", label: "Saint Pierre and Miquelon" },
    { value: "VC", label: "Saint Vincent and the Grenadines" },
    { value: "WS", label: "Samoa" },
    { value: "SM", label: "San Marino" },
    { value: "ST", label: "Sao Tome and Principe" },
    { value: "SA", label: "Saudi Arabia" },
    { value: "SN", label: "Senegal" },
    { value: "RS", label: "Serbia" },
    { value: "SC", label: "Seychelles" },
    { value: "SL", label: "Sierra Leone" },
    { value: "SG", label: "Singapore" },
    { value: "SX", label: "Sint Maarten (Dutch part)" },
    { value: "SK", label: "Slovakia" },
    { value: "SI", label: "Slovenia" },
    { value: "SB", label: "Solomon Islands" },
    { value: "SO", label: "Somalia" },
    { value: "ZA", label: "South Africa" },
    { value: "GS", label: "South Georgia and the South Sandwich Islands" },
    { value: "SS", label: "South Sudan" },
    { value: "ES", label: "Spain" },
    { value: "LK", label: "Sri Lanka" },
    { value: "SR", label: "Suriname" },
    { value: "SJ", label: "Svalbard and Jan Mayen" },
    { value: "SE", label: "Sweden" },
    { value: "CH", label: "Switzerland" },
    { value: "TW", label: "Taiwan" },
    { value: "TJ", label: "Tajikistan" },
    { value: "TZ", label: "Tanzania, United Republic of" },
    { value: "TH", label: "Thailand" },
    { value: "TL", label: "Timor-Leste" },
    { value: "TG", label: "Togo" },
    { value: "TK", label: "Tokelau" },
    { value: "TO", label: "Tonga" },
    { value: "TT", label: "Trinidad and Tobago" },
    { value: "TN", label: "Tunisia" },
    { value: "TR", label: "T�rkiye" },
    { value: "TM", label: "Turkmenistan" },
    { value: "TC", label: "Turks and Caicos Islands" },
    { value: "TV", label: "Tuvalu" },
    { value: "UG", label: "Uganda" },
    { value: "UA", label: "Ukraine" },
    { value: "AE", label: "United Arab Emirates" },
    { value: "GB", label: "United Kingdom" },
    { value: "US", label: "United States" },
    { value: "UY", label: "Uruguay" },
    { value: "UZ", label: "Uzbekistan" },
    { value: "VU", label: "Vanuatu" },
    { value: "VE", label: "Venezuela, Bolivarian Republic of" },
    { value: "VN", label: "Vietnam" },
    { value: "VG", label: "Virgin Islands, British" },
    { value: "WF", label: "Wallis and Futuna" },
    { value: "EH", label: "Western Sahara" },
    { value: "YE", label: "Yemen" },
    { value: "ZM", label: "Zambia" },
    { value: "ZW", label: "Zimbabwe" }
];

// State/Province options data
const states = [
    { value: "", label: "--None--" },
    { value: "AC", label: "Acre" },
    { value: "AG", label: "Agrigento" },
    { value: "AG", label: "Aguascalientes" },
    { value: "05", label: "Aichi" },
    { value: "02", label: "Akita" },
    { value: "AL", label: "Alabama" },
    { value: "AL", label: "Alagoas" },
    { value: "AK", label: "Alaska" },
    { value: "AB", label: "Alberta" },
    { value: "AL", label: "Alessandria" },
    { value: "AP", label: "Amap�" },
    { value: "AM", label: "Amazonas" },
    { value: "AN", label: "Ancona" },
    { value: "AN", label: "Andaman and Nicobar Islands" },
    { value: "AP", label: "Andhra Pradesh" },
    { value: "34", label: "Anhui" },
    { value: "23", label: "Aomori" },
    { value: "AO", label: "Aosta" },
    { value: "AR", label: "Arezzo" },
    { value: "AZ", label: "Arizona" },
    { value: "AR", label: "Arkansas" },
    { value: "AR", label: "Arunachal Pradesh" },
    { value: "AP", label: "Ascoli Piceno" },
    { value: "AS", label: "Assam" },
    { value: "AT", label: "Asti" },
    { value: "ACT", label: "Australian Capital Territory" },
    { value: "AV", label: "Avellino" },
    { value: "BA", label: "Bahia" },
    { value: "BC", label: "Baja California" },
    { value: "BS", label: "Baja California Sur" },
    { value: "BA", label: "Bari" },
    { value: "BT", label: "Barletta-Andria-Trani" },
    { value: "11", label: "Beijing" },
    { value: "BL", label: "Belluno" },
    { value: "BN", label: "Benevento" },
    { value: "BG", label: "Bergamo" },
    { value: "BI", label: "Biella" },
    { value: "BR", label: "Bihar" },
    { value: "BO", label: "Bologna" },
    { value: "BZ", label: "Bolzano" },
    { value: "BS", label: "Brescia" },
    { value: "BR", label: "Brindisi" },
    { value: "BC", label: "British Columbia" },
    { value: "CA", label: "Cagliari" },
    { value: "CA", label: "California" },
    { value: "CL", label: "Caltanissetta" },
    { value: "CM", label: "Campeche" },
    { value: "CB", label: "Campobasso" },
    { value: "CI", label: "Carbonia-Iglesias" },
    { value: "CW", label: "Carlow" },
    { value: "CE", label: "Caserta" },
    { value: "CT", label: "Catania" },
    { value: "CZ", label: "Catanzaro" },
    { value: "CN", label: "Cavan" },
    { value: "CE", label: "Cear�" },
    { value: "CH", label: "Chandigarh" },
    { value: "CT", label: "Chhattisgarh" },
    { value: "CS", label: "Chiapas" },
    { value: "12", label: "Chiba" },
    { value: "CH", label: "Chieti" },
    { value: "CH", label: "Chihuahua" },
    { value: "50", label: "Chongqing" },
    { value: "CE", label: "Clare" },
    { value: "CO", label: "Coahuila" },
    { value: "CL", label: "Colima" },
    { value: "CO", label: "Colorado" },
    { value: "CO", label: "Como" },
    { value: "CT", label: "Connecticut" },
    { value: "CO", label: "Cork" },
    { value: "CS", label: "Cosenza" },
    { value: "CR", label: "Cremona" },
    { value: "KR", label: "Crotone" },
    { value: "CN", label: "Cuneo" },
    { value: "DN", label: "Dadra and Nagar Haveli" },
    { value: "DD", label: "Daman and Diu" },
    { value: "DE", label: "Delaware" },
    { value: "DL", label: "Delhi" },
    { value: "DC", label: "District of Columbia" },
    { value: "DF", label: "Distrito Federal" },
    { value: "DL", label: "Donegal" },
    { value: "D", label: "Dublin" },
    { value: "DG", label: "Durango" },
    { value: "38", label: "Ehime" },
    { value: "EN", label: "Enna" },
    { value: "ES", label: "Esp�rito Santo" },
    { value: "DF", label: "Federal District" },
    { value: "FM", label: "Fermo" },
    { value: "FE", label: "Ferrara" },
    { value: "FI", label: "Florence" },
    { value: "FL", label: "Florida" },
    { value: "FG", label: "Foggia" },
    { value: "FC", label: "Forl�-Cesena" },
    { value: "FR", label: "Frosinone" },
    { value: "35", label: "Fujian" },
    { value: "18", label: "Fukui" },
    { value: "40", label: "Fukuoka" },
    { value: "07", label: "Fukushima" },
    { value: "G", label: "Galway" },
    { value: "62", label: "Gansu" },
    { value: "GE", label: "Genoa" },
    { value: "GA", label: "Georgia" },
    { value: "21", label: "Gifu" },
    { value: "GA", label: "Goa" },
    { value: "GO", label: "Goi�s" },
    { value: "GO", label: "Gorizia" },
    { value: "GR", label: "Grosseto" },
    { value: "GT", label: "Guanajuato" },
    { value: "44", label: "Guangdong" },
    { value: "45", label: "Guangxi" },
    { value: "GR", label: "Guerrero" },
    { value: "52", label: "Guizhou" },
    { value: "GJ", label: "Gujarat" },
    { value: "10", label: "Gunma" },
    { value: "46", label: "Hainan" },
    { value: "HR", label: "Haryana" },
    { value: "HI", label: "Hawaii" },
    { value: "13", label: "Hebei" },
    { value: "23", label: "Heilongjiang" },
    { value: "41", label: "Henan" },
    { value: "HG", label: "Hidalgo" },
    { value: "HP", label: "Himachal Pradesh" },
    { value: "34", label: "Hiroshima" },
    { value: "01", label: "Hokkaido" },
    { value: "91", label: "Hong Kong" },
    { value: "42", label: "Hubei" },
    { value: "43", label: "Hunan" },
    { value: "28", label: "Hyogo" },
    { value: "08", label: "Ibaraki" },
    { value: "ID", label: "Idaho" },
    { value: "IL", label: "Illinois" },
    { value: "IM", label: "Imperia" },
    { value: "IN", label: "Indiana" },
    { value: "IA", label: "Iowa" },
    { value: "IS", label: "Isernia" },
    { value: "17", label: "Ishikawa" },
    { value: "03", label: "Iwate" },
    { value: "JA", label: "Jalisco" },
    { value: "JK", label: "Jammu and Kashmir" },
    { value: "JH", label: "Jharkhand" },
    { value: "32", label: "Jiangsu" },
    { value: "36", label: "Jiangxi" },
    { value: "22", label: "Jilin" },
    { value: "37", label: "Kagawa" },
    { value: "46", label: "Kagoshima" },
    { value: "14", label: "Kanagawa" },
    { value: "KS", label: "Kansas" },
    { value: "KA", label: "Karnataka" },
    { value: "KY", label: "Kentucky" },
    { value: "KL", label: "Kerala" },
    { value: "KY", label: "Kerry" },
    { value: "KE", label: "Kildare" },
    { value: "KK", label: "Kilkenny" },
    { value: "39", label: "Kochi" },
    { value: "43", label: "Kumamoto" },
    { value: "26", label: "Kyoto" },
    { value: "AQ", label: "L'Aquila" },
    { value: "LD", label: "Lakshadweep" },
    { value: "LS", label: "Laois" },
    { value: "SP", label: "La Spezia" },
    { value: "LT", label: "Latina" },
    { value: "LE", label: "Lecce" },
    { value: "LC", label: "Lecco" },
    { value: "LM", label: "Leitrim" },
    { value: "21", label: "Liaoning" },
    { value: "LK", label: "Limerick" },
    { value: "LI", label: "Livorno" },
    { value: "LO", label: "Lodi" },
    { value: "LD", label: "Longford" },
    { value: "LA", label: "Louisiana" },
    { value: "LH", label: "Louth" },
    { value: "LU", label: "Lucca" },
    { value: "92", label: "Macao" },
    { value: "MC", label: "Macerata" },
    { value: "MP", label: "Madhya Pradesh" },
    { value: "MH", label: "Maharashtra" },
    { value: "ME", label: "Maine" },
    { value: "MN", label: "Manipur" },
    { value: "MB", label: "Manitoba" },
    { value: "MN", label: "Mantua" },
    { value: "MA", label: "Maranh�o" },
    { value: "MD", label: "Maryland" },
    { value: "MS", label: "Massa and Carrara" },
    { value: "MA", label: "Massachusetts" },
    { value: "MT", label: "Matera" },
    { value: "MT", label: "Mato Grosso" },
    { value: "MS", label: "Mato Grosso do Sul" },
    { value: "MO", label: "Mayo" },
    { value: "MH", label: "Meath" },
    { value: "VS", label: "Medio Campidano" },
    { value: "ML", label: "Meghalaya" },
    { value: "ME", label: "Messina" },
    { value: "ME", label: "Mexico State" },
    { value: "MI", label: "Michigan" },
    { value: "MI", label: "Michoac�n" },
    { value: "24", label: "Mie" },
    { value: "MI", label: "Milan" },
    { value: "MG", label: "Minas Gerais" },
    { value: "MN", label: "Minnesota" },
    { value: "MS", label: "Mississippi" },
    { value: "MO", label: "Missouri" },
    { value: "04", label: "Miyagi" },
    { value: "45", label: "Miyazaki" },
    { value: "MZ", label: "Mizoram" },
    { value: "MO", label: "Modena" },
    { value: "MN", label: "Monaghan" },
    { value: "MT", label: "Montana" },
    { value: "MB", label: "Monza and Brianza" },
    { value: "MO", label: "Morelos" },
    { value: "NL", label: "Nagaland" },
    { value: "20", label: "Nagano" },
    { value: "42", label: "Nagasaki" },
    { value: "NA", label: "Naples" },
    { value: "29", label: "Nara" },
    { value: "NA", label: "Nayarit" },
    { value: "NE", label: "Nebraska" },
    { value: "15", label: "Nei Mongol" },
    { value: "NV", label: "Nevada" },
    { value: "NB", label: "New Brunswick" },
    { value: "NL", label: "Newfoundland and Labrador" },
    { value: "NH", label: "New Hampshire" },
    { value: "NJ", label: "New Jersey" },
    { value: "NM", label: "New Mexico" },
    { value: "NSW", label: "New South Wales" },
    { value: "NY", label: "New York" },
    { value: "15", label: "Niigata" },
    { value: "64", label: "Ningxia" },
    { value: "NC", label: "North Carolina" },
    { value: "ND", label: "North Dakota" },
    { value: "NT", label: "Northern Territory" },
    { value: "NT", label: "Northwest Territories" },
    { value: "NO", label: "Novara" },
    { value: "NS", label: "Nova Scotia" },
    { value: "NL", label: "Nuevo Le�n" },
    { value: "NU", label: "Nunavut" },
    { value: "NU", label: "Nuoro" },
    { value: "OA", label: "Oaxaca" },
    { value: "OR", label: "Odisha" },
    { value: "OY", label: "Offaly" },
    { value: "OG", label: "Ogliastra" },
    { value: "OH", label: "Ohio" },
    { value: "44", label: "Oita" },
    { value: "33", label: "Okayama" },
    { value: "47", label: "Okinawa" },
    { value: "OK", label: "Oklahoma" },
    { value: "OT", label: "Olbia-Tempio" },
    { value: "ON", label: "Ontario" },
    { value: "OR", label: "Oregon" },
    { value: "OR", label: "Oristano" },
    { value: "27", label: "Osaka" },
    { value: "PD", label: "Padua" },
    { value: "PA", label: "Palermo" },
    { value: "PA", label: "Par�" },
    { value: "PB", label: "Para�ba" },
    { value: "PR", label: "Paran�" },
    { value: "PR", label: "Parma" },
    { value: "PV", label: "Pavia" },
    { value: "PA", label: "Pennsylvania" },
    { value: "PE", label: "Pernambuco" },
    { value: "PG", label: "Perugia" },
    { value: "PU", label: "Pesaro and Urbino" },
    { value: "PE", label: "Pescara" },
    { value: "PC", label: "Piacenza" },
    { value: "PI", label: "Piau�" },
    { value: "PI", label: "Pisa" },
    { value: "PT", label: "Pistoia" },
    { value: "PN", label: "Pordenone" },
    { value: "PZ", label: "Potenza" },
    { value: "PO", label: "Prato" },
    { value: "PE", label: "Prince Edward Island" },
    { value: "PY", label: "Puducherry" },
    { value: "PB", label: "Puebla" },
    { value: "PB", label: "Punjab" },
    { value: "63", label: "Qinghai" },
    { value: "QC", label: "Quebec" },
    { value: "QLD", label: "Queensland" },
    { value: "QE", label: "Quer�taro" },
    { value: "QR", label: "Quintana Roo" },
    { value: "RG", label: "Ragusa" },
    { value: "RJ", label: "Rajasthan" },
    { value: "RA", label: "Ravenna" },
    { value: "RC", label: "Reggio Calabria" },
    { value: "RE", label: "Reggio Emilia" },
    { value: "RI", label: "Rhode Island" },
    { value: "RI", label: "Rieti" },
    { value: "RN", label: "Rimini" },
    { value: "RJ", label: "Rio de Janeiro" },
    { value: "RN", label: "Rio Grande do Norte" },
    { value: "RS", label: "Rio Grande do Sul" },
    { value: "RM", label: "Rome" },
    { value: "RO", label: "Rond�nia" },
    { value: "RR", label: "Roraima" },
    { value: "RN", label: "Roscommon" },
    { value: "RO", label: "Rovigo" },
    { value: "41", label: "Saga" },
    { value: "11", label: "Saitama" },
    { value: "SA", label: "Salerno" },
    { value: "SL", label: "San Luis Potos�" },
    { value: "SC", label: "Santa Catarina" },
    { value: "SP", label: "S�o Paulo" },
    { value: "SK", label: "Saskatchewan" },
    { value: "SS", label: "Sassari" },
    { value: "SV", label: "Savona" },
    { value: "SE", label: "Sergipe" },
    { value: "61", label: "Shaanxi" },
    { value: "37", label: "Shandong" },
    { value: "31", label: "Shanghai" },
    { value: "14", label: "Shanxi" },
    { value: "25", label: "Shiga" },
    { value: "32", label: "Shimane" },
    { value: "22", label: "Shizuoka" },
    { value: "51", label: "Sichuan" },
    { value: "SI", label: "Siena" },
    { value: "SK", label: "Sikkim" },
    { value: "SI", label: "Sinaloa" },
    { value: "SO", label: "Sligo" },
    { value: "SO", label: "Sondrio" },
    { value: "SO", label: "Sonora" },
    { value: "SA", label: "South Australia" },
    { value: "SC", label: "South Carolina" },
    { value: "SD", label: "South Dakota" },
    { value: "SR", label: "Syracuse" },
    { value: "TB", label: "Tabasco" },
    { value: "71", label: "Taiwan" },
    { value: "TM", label: "Tamaulipas" },
    { value: "TN", label: "Tamil Nadu" },
    { value: "TA", label: "Taranto" },
    { value: "TAS", label: "Tasmania" },
    { value: "TG", label: "Telangana" },
    { value: "TN", label: "Tennessee" },
    { value: "TE", label: "Teramo" },
    { value: "TR", label: "Terni" },
    { value: "TX", label: "Texas" },
    { value: "12", label: "Tianjin" },
    { value: "TA", label: "Tipperary" },
    { value: "TL", label: "Tlaxcala" },
    { value: "TO", label: "Tocantins" },
    { value: "09", label: "Tochigi" },
    { value: "36", label: "Tokushima" },
    { value: "13", label: "Tokyo" },
    { value: "31", label: "Tottori" },
    { value: "16", label: "Toyama" },
    { value: "TP", label: "Trapani" },
    { value: "TN", label: "Trento" },
    { value: "TV", label: "Treviso" },
    { value: "TS", label: "Trieste" },
    { value: "TR", label: "Tripura" },
    { value: "TO", label: "Turin" },
    { value: "UD", label: "Udine" },
    { value: "UT", label: "Utah" },
    { value: "UT", label: "Uttarakhand" },
    { value: "UP", label: "Uttar Pradesh" },
    { value: "VA", label: "Varese" },
    { value: "VE", label: "Venice" },
    { value: "VE", label: "Veracruz" },
    { value: "VB", label: "Verbano-Cusio-Ossola" },
    { value: "VC", label: "Vercelli" },
    { value: "VT", label: "Vermont" },
    { value: "VR", label: "Verona" },
    { value: "VV", label: "Vibo Valentia" },
    { value: "VI", label: "Vicenza" },
    { value: "VIC", label: "Victoria" },
    { value: "VA", label: "Virginia" },
    { value: "VT", label: "Viterbo" },
    { value: "30", label: "Wakayama" },
    { value: "WA", label: "Washington" },
    { value: "WD", label: "Waterford" },
    { value: "WB", label: "West Bengal" },
    { value: "WA", label: "Western Australia" },
    { value: "WH", label: "Westmeath" },
    { value: "WV", label: "West Virginia" },
    { value: "WX", label: "Wexford" },
    { value: "WW", label: "Wicklow" },
    { value: "WI", label: "Wisconsin" },
    { value: "WY", label: "Wyoming" },
    { value: "65", label: "Xinjiang" },
    { value: "54", label: "Xizang" },
    { value: "06", label: "Yamagata" },
    { value: "35", label: "Yamaguchi" },
    { value: "19", label: "Yamanashi" },
    { value: "YU", label: "Yucat�n" },
    { value: "YT", label: "Yukon Territories" },
    { value: "53", label: "Yunnan" },
    { value: "ZA", label: "Zacatecas" },
    { value: "33", label: "Zhejiang" }
];

/**
 * Populates a select element with options from a data array
 * @param {string} selectId - The ID of the select element
 * @param {Array} optionsData - Array of objects with value and label properties
 */
function populateSelect(selectId, optionsData) {
    const selectElement = document.getElementById(selectId);

    if (!selectElement) {
        console.error(`Select element with ID "${selectId}" not found`);
        return;
    }

    // Clear existing options
    selectElement.innerHTML = '';

    // Add options from data array
    optionsData.forEach(option => {
        const optionElement = document.createElement('option');
        optionElement.value = option.value;
        optionElement.textContent = option.label;
        selectElement.appendChild(optionElement);
    });
}

// Initialize page when DOM is fully loaded
document.addEventListener('DOMContentLoaded', function() {
    // Check if we should show thank you page or form
    checkSubmissionStatus();

    // Populate dropdown options
    populateSelect('country_code', countries);
    populateSelect('state_code', states);

    // Add form submission handler to convert date format
    const form = document.getElementById('leadForm');
    if (form) {
        form.addEventListener('submit', handleFormSubmit);
    }
});
